# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & deploy dev.RIMAROK.com

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: touch .env.production
      - run: echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> .env.production
      - run: echo "MOTIFS_DATABASE_ID=${{ secrets.MOTIFS_DATABASE_ID }}" >> .env.production

      - run: npm i
      - run: npm run build
      - run: npm run build:apps

      - name: FTP dev environment
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public
          server-dir: ${{ secrets.FTP_DEV_DIR }}
